// <auto-generated />
using System;
using ActuarialTranslationEngine.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActuarialTranslationEngine.Persistence.Migrations
{
    [DbContext(typeof(ActuarialDbContext))]
    partial class ActuarialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ActuarialTranslationEngine.Core.Persistence.TranslationJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetSheet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkbookSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TranslationJobs");
                });

            modelBuilder.Entity("ActuarialTranslationEngine.Core.Persistence.TranslationPartitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisruptiveNodesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalAuditableMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedCSharpMirrorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCertified")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartitionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VarianceDelta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("TranslationPartitions");
                });

            modelBuilder.Entity("ActuarialTranslationEngine.Core.Persistence.TranslationPartitionEntity", b =>
                {
                    b.HasOne("ActuarialTranslationEngine.Core.Persistence.TranslationJobEntity", "Job")
                        .WithMany("Partitions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ActuarialTranslationEngine.Core.Persistence.TranslationJobEntity", b =>
                {
                    b.Navigation("Partitions");
                });
#pragma warning restore 612, 618
        }
    }
}
